export default [
  { "id": 133, "name": "Oakland Athletics", "short": "OAK", bgClass: 'bg-oak-main' },
  { "id": 134, "name": "Pittsburgh Pirates", "short": "PIT", bgClass: 'bg-pit-main' },
  { "id": 135, "name": "San Diego Padres", "short": "SD", bgClass: 'bg-sd-main' },
  { "id": 136, "name": "Seattle Mariners", "short": "SEA", bgClass: 'bg-sea-main' },
  { "id": 137, "name": "San Francisco Giants", "short": "SF", bgClass: 'bg-sf-main' },
  { "id": 138, "name": "St. Louis Cardinals", "short": "STL", bgClass: 'bg-stl-main' },
  { "id": 139, "name": "Tampa Bay Rays", "short": "TB", bgClass: 'bg-tb-main' },
  { "id": 140, "name": "Texas Rangers", "short": "TEX", bgClass: 'bg-tex-main' },
  { "id": 141, "name": "Toronto Blue Jays", "short": "TOR", bgClass: 'bg-tor-main' },
  { "id": 142, "name": "Minnesota Twins", "short": "MIN", bgClass: 'bg-min-main' },
  { "id": 143, "name": "Philadelphia Phillies", "short": "PHI", bgClass: 'bg-phi-main' },
  { "id": 144, "name": "Atlanta Braves", "short": "ATL", bgClass: 'bg-atl-main' },
  { "id": 145, "name": "Chicago White Sox", "short": "CWS", bgClass: 'bg-cws-main' },
  { "id": 146, "name": "Miami Marlins", "short": "MIA", bgClass: 'bg-mia-main' },
  { "id": 147, "name": "New York Yankees", "short": "NYY", bgClass: 'bg-nyy-main' },
  { "id": 158, "name": "Milwaukee Brewers", "short": "MIL", bgClass: 'bg-mil-main' },
  { "id": 108, "name": "Los Angeles Angels", "short": "LAA", bgClass: 'bg-laa-main' },
  { "id": 109, "name": "Arizona Diamondbacks", "short": "ARI", bgClass: 'bg-ari-main' },
  { "id": 110, "name": "Baltimore Orioles", "short": "BAL", bgClass: 'bg-bal-main' },
  { "id": 111, "name": "Boston Red Sox", "short": "BOS", bgClass: 'bg-bos-main' },
  { "id": 112, "name": "Chicago Cubs", "short": "CHC", bgClass: 'bg-chc-main' },
  { "id": 113, "name": "Cincinnati Reds", "short": "CIN", bgClass: 'bg-cin-main' },
  { "id": 114, "name": "Cleveland Indians", "short": "CLE", bgClass: 'bg-cle-main' },
  { "id": 115, "name": "Colorado Rockies", "short": "COL", bgClass: 'bg-col-main' },
  { "id": 116, "name": "Detroit Tigers", "short": "DET", bgClass: 'bg-det-main' },
  { "id": 117, "name": "Houston Astros", "short": "HOU", bgClass: 'bg-hou-main' },
  { "id": 118, "name": "Kansas City Royals", "short": "KC", bgClass: 'bg-kc-main' },
  { "id": 119, "name": "Los Angeles Dodgers", "short": "LAD", bgClass: 'bg-lad-main' },
  { "id": 120, "name": "Washington Nationals", "short": "WSH", bgClass: 'bg-wsh-main' },
  { "id": 121, "name": "New York Mets", "short": "NYM", bgClass: 'bg-nym-main' }
]
