export default [
  { id: 133, name: 'Oakland Athletics', short: 'OAK', mainBackground: 'bg-oak-main', mainText: 'text-oak-text-main', secondaryBackground: 'bg-oak-secondary', secondaryText: 'text-oak-text-secondary' },
  { id: 134, name: 'Pittsburgh Pirates', short: 'PIT', mainBackground: 'bg-pit-main', mainText: 'text-pit-text-main', secondaryBackground: 'bg-pit-secondary', secondaryText: 'text-pit-text-secondary' },
  { id: 135, name: 'San Diego Padres', short: 'SD', mainBackground: 'bg-sd-main', mainText: 'text-sd-text-main', secondaryBackground: 'bg-sd-secondary', secondaryText: 'text-sd-text-secondary' },
  { id: 136, name: 'Seattle Mariners', short: 'SEA', mainBackground: 'bg-sea-main', mainText: 'text-sea-text-main', secondaryBackground: 'bg-sea-secondary', secondaryText: 'text-sea-text-secondary' },
  { id: 137, name: 'San Francisco Giants', short: 'SF', conflicts: ['CWS'], mainBackground: 'bg-sf-main', mainText: 'text-sf-text-main', secondaryBackground: 'bg-sf-secondary', secondaryText: 'text-sf-text-secondary' },
  { id: 138, name: 'St. Louis Cardinals', short: 'STL', mainBackground: 'bg-stl-main', mainText: 'text-stl-text-main', secondaryBackground: 'bg-stl-secondary', secondaryText: 'text-stl-text-secondary' },
  { id: 139, name: 'Tampa Bay Rays', short: 'TB', mainBackground: 'bg-tb-main', mainText: 'text-tb-text-main', secondaryBackground: 'bg-tb-secondary', secondaryText: 'text-tb-text-secondary' },
  { id: 140, name: 'Texas Rangers', short: 'TEX', mainBackground: 'bg-tex-main', mainText: 'text-tex-text-main', secondaryBackground: 'bg-tex-secondary', secondaryText: 'text-tex-text-secondary' },
  { id: 141, name: 'Toronto Blue Jays', short: 'TOR', mainBackground: 'bg-tor-main', mainText: 'text-tor-text-main', secondaryBackground: 'bg-tor-secondary', secondaryText: 'text-tor-text-secondary' },
  { id: 142, name: 'Minnesota Twins', short: 'MIN', mainBackground: 'bg-min-main', mainText: 'text-min-text-main', secondaryBackground: 'bg-min-secondary', secondaryText: 'text-min-text-secondary' },
  { id: 143, name: 'Philadelphia Phillies', short: 'PHI', mainBackground: 'bg-phi-main', mainText: 'text-phi-text-main', secondaryBackground: 'bg-phi-secondary', secondaryText: 'text-phi-text-secondary' },
  { id: 144, name: 'Atlanta Braves', short: 'ATL', mainBackground: 'bg-atl-main', mainText: 'text-atl-text-main', secondaryBackground: 'bg-atl-secondary', secondaryText: 'text-atl-text-secondary' },
  { id: 145, name: 'Chicago White Sox', short: 'CWS', conflicts: ['SF'], mainBackground: 'bg-cws-main', mainText: 'text-cws-text-main', secondaryBackground: 'bg-cws-secondary', secondaryText: 'text-cws-text-secondary' },
  { id: 146, name: 'Miami Marlins',  short: 'MIA', mainBackground: 'bg-mia-main', mainText: 'text-mia-text-main', secondaryBackground: 'bg-mia-secondary', secondaryText: 'text-mia-text-secondary' },
  { id: 147, name: 'New York Yankees', short: 'NYY', priority: 1, conflicts: ['DET'], mainBackground: 'bg-nyy-main', mainText: 'text-nyy-text-main', secondaryBackground: 'bg-nyy-secondary', secondaryText: 'text-nyy-text-secondary' },
  { id: 158, name: 'Milwaukee Brewers', short: 'MIL', mainBackground: 'bg-mil-main', mainText: 'text-mil-text-main', secondaryBackground: 'bg-mil-secondary', secondaryText: 'text-mil-text-secondary' },
  { id: 108, name: 'Los Angeles Angels', short: 'LAA', mainBackground: 'bg-laa-main', mainText: 'text-laa-text-main', secondaryBackground: 'bg-laa-secondary', secondaryText: 'text-laa-text-secondary' },
  { id: 109, name: 'Arizona Diamondbacks', short: 'ARI', mainBackground: 'bg-ari-main', mainText: 'text-ari-text-main', secondaryBackground: 'bg-ari-secondary', secondaryText: 'text-ari-text-secondary' },
  { id: 110, name: 'Baltimore Orioles', short: 'BAL', mainBackground: 'bg-bal-main', mainText: 'text-bal-text-main', secondaryBackground: 'bg-bal-secondary', secondaryText: 'text-bal-text-secondary' },
  { id: 111, name: 'Boston Red Sox', short: 'BOS', mainBackground: 'bg-bos-main', mainText: 'text-bos-text-main', secondaryBackground: 'bg-bos-secondary', secondaryText: 'text-bos-text-secondary' },
  { id: 112, name: 'Chicago Cubs', short: 'CHC', mainBackground: 'bg-chc-main', mainText: 'text-chc-text-main', secondaryBackground: 'bg-chc-secondary', secondaryText: 'text-chc-text-secondary' },
  { id: 113, name: 'Cincinnati Reds', short: 'CIN', mainBackground: 'bg-cin-main', mainText: 'text-cin-text-main', secondaryBackground: 'bg-cin-secondary', secondaryText: 'text-cin-text-secondary' },
  { id: 114, name: 'Cleveland Indians', short: 'CLE', mainBackground: 'bg-cle-main', mainText: 'text-cle-text-main', secondaryBackground: 'bg-cle-secondary', secondaryText: 'text-cle-text-secondary' },
  { id: 115, name: 'Colorado Rockies', short: 'COL', mainBackground: 'bg-col-main', mainText: 'text-col-text-main', secondaryBackground: 'bg-col-secondary', secondaryText: 'text-col-text-secondary' },
  { id: 116, name: 'Detroit Tigers', short: 'DET', conflicts: ['NYY'], mainBackground: 'bg-det-main', mainText: 'text-det-text-main', secondaryBackground: 'bg-det-secondary', secondaryText: 'text-det-text-secondary' },
  { id: 117, name: 'Houston Astros', short: 'HOU', mainBackground: 'bg-hou-main', mainText: 'text-hou-text-main', secondaryBackground: 'bg-hou-secondary', secondaryText: 'text-hou-text-secondary' },
  { id: 118, name: 'Kansas City Royals', short: 'KC', mainBackground: 'bg-kc-main', mainText: 'text-kc-text-main', secondaryBackground: 'bg-kc-secondary', secondaryText: 'text-kc-text-secondary' },
  { id: 119, name: 'Los Angeles Dodgers', short: 'LAD', mainBackground: 'bg-lad-main', mainText: 'text-lad-text-main', secondaryBackground: 'bg-lad-secondary', secondaryText: 'text-lad-text-secondary' },
  { id: 120, name: 'Washington Nationals', short: 'WSH', mainBackground: 'bg-wsh-main', mainText: 'text-wsh-text-main', secondaryBackground: 'bg-wsh-secondary', secondaryText: 'text-wsh-text-secondary' },
  { id: 121, name: 'New York Mets', short: 'NYM', mainBackground: 'bg-nym-main', mainText: 'text-nym-text-main', secondaryBackground: 'bg-nym-secondary', secondaryText: 'text-nym-text-secondary' }
]
