export default [
  {
    id: 133,
    name: 'Oakland Athletics',
    short: 'OAK',
    mainBackground: 'bg-oak-main',
    mainColor: 'text-oak-main',
    mainText: 'text-oak-text-main',
    secondaryBackground: 'bg-oak-secondary',
    secondaryText: 'text-oak-text-secondary',
    stroke: 'stroke-oak-main',
    divisionId: 200,
  },
  {
    id: 117,
    name: 'Houston Astros',
    short: 'HOU',
    mainBackground: 'bg-hou-main',
    mainColor: 'text-hou-main',
    mainText: 'text-hou-text-main',
    secondaryBackground: 'bg-hou-secondary',
    secondaryText: 'text-hou-text-secondary',
    stroke: 'stroke-hou-main',
    divisionId: 200,
  },
  {
    id: 136,
    name: 'Seattle Mariners',
    short: 'SEA',
    mainBackground: 'bg-sea-main',
    mainColor: 'text-sea-main',
    mainText: 'text-sea-text-main',
    secondaryBackground: 'bg-sea-secondary',
    secondaryText: 'text-sea-text-secondary',
    stroke: 'stroke-sea-main',
    divisionId: 200,
  },
  {
    id: 140,
    name: 'Texas Rangers',
    short: 'TEX',
    mainBackground: 'bg-tex-main',
    mainColor: 'text-tex-main',
    mainText: 'text-tex-text-main',
    secondaryBackground: 'bg-tex-secondary',
    secondaryText: 'text-tex-text-secondary',
    stroke: 'stroke-tex-main',
    divisionId: 200,
  },
  {
    id: 108,
    name: 'Los Angeles Angels',
    short: 'LAA',
    mainBackground: 'bg-laa-main',
    mainColor: 'text-laa-main',
    mainText: 'text-laa-text-main',
    secondaryBackground: 'bg-laa-secondary',
    secondaryText: 'text-laa-text-secondary',
    stroke: 'stroke-laa-main',
    divisionId: 200,
  },
  {
    id: 142,
    name: 'Minnesota Twins',
    short: 'MIN',
    mainBackground: 'bg-min-main',
    mainColor: 'text-min-main',
    mainText: 'text-min-text-main',
    secondaryBackground: 'bg-min-secondary',
    secondaryText: 'text-min-text-secondary',
    stroke: 'stroke-min-main',
    divisionId: 202,
  },
  {
    id: 145,
    name: 'Chicago White Sox',
    short: 'CWS',
    conflicts: ['SF'],
    mainBackground: 'bg-cws-main',
    mainColor: 'text-cws-main',
    mainText: 'text-cws-text-main',
    secondaryBackground: 'bg-cws-secondary',
    secondaryText: 'text-cws-text-secondary',
    stroke: 'stroke-cws-main',
    divisionId: 202,
  },
  {
    id: 114,
    name: 'Cleveland Indians',
    short: 'CLE',
    conflicts: ['DET', 'NYY'],
    mainBackground: 'bg-cle-main',
    mainColor: 'text-cle-main',
    mainText: 'text-cle-text-main',
    secondaryBackground: 'bg-cle-secondary',
    secondaryText: 'text-cle-text-secondary',
    stroke: 'stroke-cle-main',
    divisionId: 202,
  },
  {
    id: 116,
    name: 'Detroit Tigers',
    short: 'DET',
    conflicts: ['NYY', 'CLE'],
    mainBackground: 'bg-det-main',
    mainColor: 'text-det-main',
    mainText: 'text-det-text-main',
    secondaryBackground: 'bg-det-secondary',
    secondaryText: 'text-det-text-secondary',
    stroke: 'stroke-det-main',
    divisionId: 202,
  },
  {
    id: 118,
    name: 'Kansas City Royals',
    short: 'KC',
    mainBackground: 'bg-kc-main',
    mainColor: 'text-kc-main',
    mainText: 'text-kc-text-main',
    secondaryBackground: 'bg-kc-secondary',
    secondaryText: 'text-kc-text-secondary',
    stroke: 'stroke-kc-main',
    divisionId: 202,
  },
  {
    id: 139,
    name: 'Tampa Bay Rays',
    short: 'TB',
    mainBackground: 'bg-tb-main',
    mainColor: 'text-tb-main',
    mainText: 'text-tb-text-main',
    secondaryBackground: 'bg-tb-secondary',
    secondaryText: 'text-tb-text-secondary',
    stroke: 'stroke-tb-main',
    divisionId: 201,
  },
  {
    id: 141,
    name: 'Toronto Blue Jays',
    short: 'TOR',
    mainBackground: 'bg-tor-main',
    mainColor: 'text-tor-main',
    mainText: 'text-tor-text-main',
    secondaryBackground: 'bg-tor-secondary',
    secondaryText: 'text-tor-text-secondary',
    stroke: 'stroke-tor-main',
    divisionId: 201,
  },
  {
    id: 110,
    name: 'Baltimore Orioles',
    short: 'BAL',
    mainBackground: 'bg-bal-main',
    mainColor: 'text-bal-main',
    mainText: 'text-bal-text-main',
    secondaryBackground: 'bg-bal-secondary',
    secondaryText: 'text-bal-text-secondary',
    stroke: 'stroke-bal-main',
    divisionId: 201,
  },
  {
    id: 111,
    name: 'Boston Red Sox',
    short: 'BOS',
    mainBackground: 'bg-bos-main',
    mainColor: 'text-bos-main',
    mainText: 'text-bos-text-main',
    secondaryBackground: 'bg-bos-secondary',
    secondaryText: 'text-bos-text-secondary',
    stroke: 'stroke-bos-main',
    divisionId: 201,
  },
  {
    id: 147,
    name: 'New York Yankees',
    short: 'NYY',
    priority: 1,
    conflicts: ['DET', 'CLE'],
    mainBackground: 'bg-nyy-main',
    mainColor: 'text-nyy-main',
    mainText: 'text-nyy-text-main',
    secondaryBackground: 'bg-nyy-secondary',
    secondaryText: 'text-nyy-text-secondary',
    stroke: 'stroke-nyy-main',
    divisionId: 201,
  },
  {
    id: 135,
    name: 'San Diego Padres',
    short: 'SD',
    mainBackground: 'bg-sd-main',
    mainColor: 'text-sd-main',
    mainText: 'text-sd-text-main',
    secondaryBackground: 'bg-sd-secondary',
    secondaryText: 'text-sd-text-secondary',
    stroke: 'stroke-sd-main',
    divisionId: 203,
  },
  {
    id: 137,
    name: 'San Francisco Giants',
    short: 'SF',
    conflicts: ['CWS'],
    mainBackground: 'bg-sf-main',
    mainColor: 'text-sf-main',
    mainText: 'text-sf-text-main',
    secondaryBackground: 'bg-sf-secondary',
    secondaryText: 'text-sf-text-secondary',
    stroke: 'stroke-sf-main',
    divisionId: 203,
  },
  {
    id: 109,
    name: 'Arizona Diamondbacks',
    short: 'ARI',
    mainBackground: 'bg-ari-main',
    mainColor: 'text-ari-main',
    mainText: 'text-ari-text-main',
    secondaryBackground: 'bg-ari-secondary',
    secondaryText: 'text-ari-text-secondary',
    stroke: 'stroke-ari-main',
    divisionId: 203,
  },
  {
    id: 115,
    name: 'Colorado Rockies',
    short: 'COL',
    mainBackground: 'bg-col-main',
    mainColor: 'text-col-main',
    mainText: 'text-col-text-main',
    secondaryBackground: 'bg-col-secondary',
    secondaryText: 'text-col-text-secondary',
    stroke: 'stroke-col-main',
    divisionId: 203,
  },
  {
    id: 119,
    name: 'Los Angeles Dodgers',
    short: 'LAD',
    mainBackground: 'bg-lad-main',
    mainColor: 'text-lad-main',
    mainText: 'text-lad-text-main',
    secondaryBackground: 'bg-lad-secondary',
    secondaryText: 'text-lad-text-secondary',
    stroke: 'stroke-lad-main',
    divisionId: 203,
  },
  {
    id: 134,
    name: 'Pittsburgh Pirates',
    short: 'PIT',
    mainBackground: 'bg-pit-main',
    mainColor: 'text-pit-main',
    mainText: 'text-pit-text-main',
    secondaryBackground: 'bg-pit-secondary',
    secondaryText: 'text-pit-text-secondary',
    stroke: 'stroke-pit-main',
    divisionId: 205,
  },
  {
    id: 138,
    name: 'St. Louis Cardinals',
    short: 'STL',
    mainBackground: 'bg-stl-main',
    mainColor: 'text-stl-main',
    mainText: 'text-stl-text-main',
    secondaryBackground: 'bg-stl-secondary',
    secondaryText: 'text-stl-text-secondary',
    stroke: 'stroke-stl-main',
    divisionId: 205,
  },
  {
    id: 158,
    name: 'Milwaukee Brewers',
    short: 'MIL',
    mainBackground: 'bg-mil-main',
    mainColor: 'text-mil-main',
    mainText: 'text-mil-text-main',
    secondaryBackground: 'bg-mil-secondary',
    secondaryText: 'text-mil-text-secondary',
    stroke: 'stroke-mil-main',
    divisionId: 205,
  },
  {
    id: 112,
    name: 'Chicago Cubs',
    short: 'CHC',
    mainBackground: 'bg-chc-main',
    mainColor: 'text-chc-main',
    mainText: 'text-chc-text-main',
    secondaryBackground: 'bg-chc-secondary',
    secondaryText: 'text-chc-text-secondary',
    stroke: 'stroke-chc-main',
    divisionId: 205,
  },
  {
    id: 113,
    name: 'Cincinnati Reds',
    short: 'CIN',
    mainBackground: 'bg-cin-main',
    mainColor: 'text-cin-main',
    mainText: 'text-cin-text-main',
    secondaryBackground: 'bg-cin-secondary',
    secondaryText: 'text-cin-text-secondary',
    stroke: 'stroke-cin-main',
    divisionId: 205,
  },
  {
    id: 143,
    name: 'Philadelphia Phillies',
    short: 'PHI',
    mainBackground: 'bg-phi-main',
    mainColor: 'text-phi-main',
    mainText: 'text-phi-text-main',
    secondaryBackground: 'bg-phi-secondary',
    secondaryText: 'text-phi-text-secondary',
    stroke: 'stroke-phi-main',
    divisionId: 204,
  },
  {
    id: 144,
    name: 'Atlanta Braves',
    short: 'ATL',
    mainBackground: 'bg-atl-main',
    mainColor: 'text-atl-main',
    mainText: 'text-atl-text-main',
    secondaryBackground: 'bg-atl-secondary',
    secondaryText: 'text-atl-text-secondary',
    stroke: 'stroke-atl-main',
    divisionId: 204,
  },
  {
    id: 146,
    name: 'Miami Marlins',
    short: 'MIA',
    mainBackground: 'bg-mia-main',
    mainColor: 'text-mia-main',
    mainText: 'text-mia-text-main',
    secondaryBackground: 'bg-mia-secondary',
    secondaryText: 'text-mia-text-secondary',
    stroke: 'stroke-mia-main',
    divisionId: 204,
  },
  {
    id: 120,
    name: 'Washington Nationals',
    short: 'WSH',
    mainBackground: 'bg-wsh-main',
    mainColor: 'text-wsh-main',
    mainText: 'text-wsh-text-main',
    secondaryBackground: 'bg-wsh-secondary',
    secondaryText: 'text-wsh-text-secondary',
    stroke: 'stroke-wsh-main',
    divisionId: 204,
  },
  {
    id: 121,
    name: 'New York Mets',
    short: 'NYM',
    mainBackground: 'bg-nym-main',
    mainColor: 'text-nym-main',
    mainText: 'text-nym-text-main',
    secondaryBackground: 'bg-nym-secondary',
    secondaryText: 'text-nym-text-secondary',
    stroke: 'stroke-nym-main',
    divisionId: 204,
  },
  {
    id: 159,
    name: 'American League All-Stars',
    short: 'AL',
    mainBackground: 'bg-al-main',
    mainColor: 'text-al-main',
    mainText: 'text-al-text-main',
    secondaryBackground: 'bg-al-secondary',
    secondaryText: 'text-al-text-secondary',
    stroke: 'stroke-al-main',
    divisionId: 200,
  },
  {
    id: 160,
    name: 'National League All-Stars',
    short: 'NL',
    mainBackground: 'bg-nl-main',
    mainColor: 'text-nl-main',
    mainText: 'text-nl-text-main',
    secondaryBackground: 'bg-nl-secondary',
    secondaryText: 'text-nl-text-secondary',
    stroke: 'stroke-nl-main',
    divisionId: 204,
  },
];
